all: 
	cd structure; make
	cd excitation; make
	cd excitationM; make
	cd pirr; make
	cd aidr; make
	cd ionization; make

test: 
	cd structure; make test
	cd excitation; make test
	cd excitationM; make test
	cd pirr; make test
	cd aidr; make test
	cd ionization; make test

clean: 
	cd structure; make clean
	cd excitation; make clean
	cd excitationM; make clean
	cd pirr; make clean
	cd aidr; make clean
	cd ionization; make clean
