name: Make CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pre-configure
      run: make ./configure || echo
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
      
