name: Make CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: requirements
      run: |
        sudo apt update
        sudo apt -y install libgsl-dev libsqlite3-dev doxygen texlive-latex-base texlive-latex-extra

    - name: pre-configure
      run: make ./configure || echo

    - name: configure
      run: echo yes | ./configure --with-cpc-modules

    - name: make
      run: make

    - name: make check
      run: make check
